# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/realestatedb
spring.datasource.username=postgres
spring.datasource.password=874712
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

#SMTP settings for sending OTP emails. Configure these with your SMTP provider or local SMTP server.
#Example (Gmail SMTP) - for local development you may prefer to use a dev SMTP server or Mailtrap:
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=harshuketha@gmail.com
# If your password contains a #, escape it so it isn't treated as a comment
spring.mail.password=lpod kzsi lbnl rrdb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

